name: pptc-crawler
channels:
  - defaults
  - conda-forge
dependencies:
  - chardet=4.0.0
  - pandas=1.1.5
  - python=3.6.11
  - tqdm=4.61.0
  - unidecode=1.1.2
  - yaml=0.2.5
  - lxml
  - pip:
    - boilerpipe3==1.3
    - fasttext==0.9.2
