name: pptc
channels:
  - defaults
  - conda-forge
dependencies:
  - chardet=4.0.0
  - cld2-cffi=0.1.4
  - fuzzywuzzy=0.18.0
  - icu=64.2
  - jinja2=2.11.2
  - joblib=1.0.0
  - jpype1=1.2.0
  - nltk=3.5
  - numpy=1.19.5
  - pandas=1.1.5
  - python=3.6.11
  - pytorch=1.7.1
  - scikit-learn=0.24.0
  - scipy=1.5.3
  - setuptools=52.0.0
  - spacy=2.3.5
  - spacy-lookups-data=0.3.0
  - textacy=0.10.0
  - tika=1.24
  - tqdm=4.61.0
  - unidecode=1.1.2
  - yaml=0.2.5
  - pip:
    - boilerpipe3==1.3
    - de-core-news-lg==2.3.0
    - en-core-web-lg==2.3.1
    - fasttext==0.9.2
    - guess-language-spirit==0.5.3
    - langdetect==1.0.8
    - langid==1.1.6
    - multi-rake==0.0.1
    - pke==1.8.1
    - polyglot==16.7.4
    - pycld2==0.41
    - pycld3==0.20
    - pyicu==2.6
    - pymupdf==1.18.6
    - readabilipy==0.2.0
    - tinydb==4.4.0
    - xx-ent-wiki-sm==2.3.0
    - yake==0.4.3